spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/car_shift_manager_db
    password: '1234'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '8087'

  ssl:
      enabled: true
      key-store-password: "123456"
      key-store-type: JKS
      key-store: classpath:cetad.keystore.jks
      key-alias: localhost
