spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/car_shift_manager_db
    password: '12345678'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  security:
    user:
      name: Admin
      password: admin


server:
  port: '8087'

  ssl:
      enabled: true
      key-store-password: "123456"
      key-store-type: JKS
      key-store: classpath:cetad.keystore.jks
      key-alias: localhost
